# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d13e1a339d8e45538d2e3925a9d9bda0dcd3590984b97ff04b814861a4b675c167cc21e098da53da26d488d9770a1db3420de07272ae8aec13f1f225f050f828

test:
  secret_key_base: 92259cbb6bc8e77b3e603b99c71a01fd1e7c30cd545feb882046a063f4fc05ba214e8ba777d7ab9c7ed879dbd0cbaad382582c2e59e84ea82a2409ad067d8733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
